### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tomByrer**
I see 3 proposals.... sometimes counting 0 as first trips up even programmers ;)

### CODE REVIEW

**Comment by KristjanTammekivi** [comment]
I count 2? 
image

**Comment by Avaq** [comment]
I think OP is referring to [the wiki page](https://github.com/tc39/proposal-pipeline-operator/wiki) linked from the text they're updating:

latest-screenshot

**Comment by mAAdhaTTah** [comment]
Just for context: The thinking at the time that was written was the minimal wasn't really a "competing" proposal. You can see that in the rest of the sentence, where minimal is explained as a strawman to compare trade-offs between the two proposals under serious consideration. Dunno if that's still true or not but that's at least why it's two.

**Comment by tomByrer** [comment]
I'm confused why it is listed in the WiKi?

**Comment by tabatkins** [comment]
Closing, both for the reasons listed here ("F#" and "F# with await" weren't really separate proposals), and because the proposal advanced to Stage 2 with a chosen syntax.

**Pull request closed without merging**
