### PR TITLE
Update introductory section on 4 proposals

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
I'm putting this in its own PR so we can review the language together.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Fair, how does this sound:

> This readme is a minimal proposal, which covers the basic features of the pipeline operator

I'm considering the "minimal proposal" as a strawman / anchor of sorts for discussing the tradeoffs between the proposals. What does it gain / lose relative to the minimal proposal?

**Comment by js-choi** [comment]
Right. It’s minimal in use cases: In particular, it does not address non-function expressions, especially `await` expressions. The new proposals do so, and we're keeping the original/minimal proposal in order to compare it with the new proposals. I think. I think that language is the right idea. Thanks again for handling this.

**Comment by mAAdhaTTah** [comment]
@js-choi Fixed the wording. Also added a mention of the "original proposal as strawman" idea.

**Comment by js-choi** [comment]
Looks great to me.

**Comment by littledan** [comment]
Should the text here mention that most of the work right now is going into just two of these? That's pretty core to the status of it, and the slides at TC39 represent things this way.

**Comment by mAAdhaTTah** [comment]
@littledan It currently does:

> Formal specifications and Babel plugins for Proposals 1 & 4 are already underway to gather feedback.

We can emphasize this a bit more explicitly, if you think that's not clear.

**Comment by littledan** [comment]
Oh, I see, I missed that. I'd just delete the references to the proposals that aren't being pursued; there are always tons of different alternatives that get brought up in the course of discussion.

**Comment by mAAdhaTTah** [comment]
I had suggested that at one point, but (iirc) @zenparsing didn't want to spike Proposal 3 just yet. That said, I don't see that one advancing and would be happy to get rid of Proposals 2 & 3 and simplify down to Minimal, Smart, and F#.

**Comment by littledan** [comment]
OK, if it's controversial, this seems fine to land.

**Pull request merged**
